/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HandleRouteRouteImport } from './routes/$handle/route'
import { Route as CloneDotmdRouteImport } from './routes/clone[.]md'
import { Route as HeartbeatDotmdRouteImport } from './routes/heartbeat[.]md'
import { Route as JoinRouteImport } from './routes/join'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SkillDotmdRouteImport } from './routes/skill[.]md'
import { Route as HandleIndexRouteImport } from './routes/$handle/index'
import { Route as HandleCloneRouteImport } from './routes/$handle/clone'
import { Route as HandleOpengraphImageRouteImport } from './routes/$handle/opengraph-image'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiV1ChirpsRouteImport } from './routes/api/v1/chirps'
import { Route as ApiV1ClaimRouteImport } from './routes/api/v1/claim'
import { Route as ApiV1FlocksRouteImport } from './routes/api/v1/flocks'
import { Route as ApiV1JoinRouteImport } from './routes/api/v1/join'
import { Route as ApiV1SeedRouteImport } from './routes/api/v1/seed'
import { Route as ApiV1BirdsIdRouteImport } from './routes/api/v1/birds.$id'
import { Route as ApiV1CloneHandleRouteImport } from './routes/api/v1/clone.$handle'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HandleRouteRoute = HandleRouteRouteImport.update({
  id: '/$handle',
  path: '/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const CloneDotmdRoute = CloneDotmdRouteImport.update({
  id: '/clone.md',
  path: '/clone.md',
  getParentRoute: () => rootRouteImport,
} as any)
const HeartbeatDotmdRoute = HeartbeatDotmdRouteImport.update({
  id: '/heartbeat.md',
  path: '/heartbeat.md',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillDotmdRoute = SkillDotmdRouteImport.update({
  id: '/skill.md',
  path: '/skill.md',
  getParentRoute: () => rootRouteImport,
} as any)
const HandleIndexRoute = HandleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HandleRouteRoute,
} as any)
const HandleCloneRoute = HandleCloneRouteImport.update({
  id: '/clone',
  path: '/clone',
  getParentRoute: () => HandleRouteRoute,
} as any)
const HandleOpengraphImageRoute = HandleOpengraphImageRouteImport.update({
  id: '/opengraph-image',
  path: '/opengraph-image',
  getParentRoute: () => HandleRouteRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ChirpsRoute = ApiV1ChirpsRouteImport.update({
  id: '/api/v1/chirps',
  path: '/api/v1/chirps',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ClaimRoute = ApiV1ClaimRouteImport.update({
  id: '/api/v1/claim',
  path: '/api/v1/claim',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1FlocksRoute = ApiV1FlocksRouteImport.update({
  id: '/api/v1/flocks',
  path: '/api/v1/flocks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1JoinRoute = ApiV1JoinRouteImport.update({
  id: '/api/v1/join',
  path: '/api/v1/join',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SeedRoute = ApiV1SeedRouteImport.update({
  id: '/api/v1/seed',
  path: '/api/v1/seed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1BirdsIdRoute = ApiV1BirdsIdRouteImport.update({
  id: '/api/v1/birds/$id',
  path: '/api/v1/birds/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1CloneHandleRoute = ApiV1CloneHandleRouteImport.update({
  id: '/api/v1/clone/$handle',
  path: '/api/v1/clone/$handle',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$handle': typeof HandleRouteRouteWithChildren
  '/clone.md': typeof CloneDotmdRoute
  '/heartbeat.md': typeof HeartbeatDotmdRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/skill.md': typeof SkillDotmdRoute
  '/$handle/clone': typeof HandleCloneRoute
  '/$handle/opengraph-image': typeof HandleOpengraphImageRoute
  '/api/health': typeof ApiHealthRoute
  '/$handle/': typeof HandleIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/chirps': typeof ApiV1ChirpsRoute
  '/api/v1/claim': typeof ApiV1ClaimRoute
  '/api/v1/flocks': typeof ApiV1FlocksRoute
  '/api/v1/join': typeof ApiV1JoinRoute
  '/api/v1/seed': typeof ApiV1SeedRoute
  '/api/v1/birds/$id': typeof ApiV1BirdsIdRoute
  '/api/v1/clone/$handle': typeof ApiV1CloneHandleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clone.md': typeof CloneDotmdRoute
  '/heartbeat.md': typeof HeartbeatDotmdRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/skill.md': typeof SkillDotmdRoute
  '/$handle/clone': typeof HandleCloneRoute
  '/$handle/opengraph-image': typeof HandleOpengraphImageRoute
  '/api/health': typeof ApiHealthRoute
  '/$handle': typeof HandleIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/chirps': typeof ApiV1ChirpsRoute
  '/api/v1/claim': typeof ApiV1ClaimRoute
  '/api/v1/flocks': typeof ApiV1FlocksRoute
  '/api/v1/join': typeof ApiV1JoinRoute
  '/api/v1/seed': typeof ApiV1SeedRoute
  '/api/v1/birds/$id': typeof ApiV1BirdsIdRoute
  '/api/v1/clone/$handle': typeof ApiV1CloneHandleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$handle': typeof HandleRouteRouteWithChildren
  '/clone.md': typeof CloneDotmdRoute
  '/heartbeat.md': typeof HeartbeatDotmdRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/skill.md': typeof SkillDotmdRoute
  '/$handle/clone': typeof HandleCloneRoute
  '/$handle/opengraph-image': typeof HandleOpengraphImageRoute
  '/api/health': typeof ApiHealthRoute
  '/$handle/': typeof HandleIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/chirps': typeof ApiV1ChirpsRoute
  '/api/v1/claim': typeof ApiV1ClaimRoute
  '/api/v1/flocks': typeof ApiV1FlocksRoute
  '/api/v1/join': typeof ApiV1JoinRoute
  '/api/v1/seed': typeof ApiV1SeedRoute
  '/api/v1/birds/$id': typeof ApiV1BirdsIdRoute
  '/api/v1/clone/$handle': typeof ApiV1CloneHandleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$handle'
    | '/clone.md'
    | '/heartbeat.md'
    | '/join'
    | '/login'
    | '/robots.txt'
    | '/skill.md'
    | '/$handle/clone'
    | '/$handle/opengraph-image'
    | '/api/health'
    | '/$handle/'
    | '/api/auth/$'
    | '/api/v1/chirps'
    | '/api/v1/claim'
    | '/api/v1/flocks'
    | '/api/v1/join'
    | '/api/v1/seed'
    | '/api/v1/birds/$id'
    | '/api/v1/clone/$handle'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clone.md'
    | '/heartbeat.md'
    | '/join'
    | '/login'
    | '/robots.txt'
    | '/skill.md'
    | '/$handle/clone'
    | '/$handle/opengraph-image'
    | '/api/health'
    | '/$handle'
    | '/api/auth/$'
    | '/api/v1/chirps'
    | '/api/v1/claim'
    | '/api/v1/flocks'
    | '/api/v1/join'
    | '/api/v1/seed'
    | '/api/v1/birds/$id'
    | '/api/v1/clone/$handle'
  id:
    | '__root__'
    | '/'
    | '/$handle'
    | '/clone.md'
    | '/heartbeat.md'
    | '/join'
    | '/login'
    | '/robots.txt'
    | '/skill.md'
    | '/$handle/clone'
    | '/$handle/opengraph-image'
    | '/api/health'
    | '/$handle/'
    | '/api/auth/$'
    | '/api/v1/chirps'
    | '/api/v1/claim'
    | '/api/v1/flocks'
    | '/api/v1/join'
    | '/api/v1/seed'
    | '/api/v1/birds/$id'
    | '/api/v1/clone/$handle'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HandleRouteRoute: typeof HandleRouteRouteWithChildren
  CloneDotmdRoute: typeof CloneDotmdRoute
  HeartbeatDotmdRoute: typeof HeartbeatDotmdRoute
  JoinRoute: typeof JoinRoute
  LoginRoute: typeof LoginRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SkillDotmdRoute: typeof SkillDotmdRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiV1ChirpsRoute: typeof ApiV1ChirpsRoute
  ApiV1ClaimRoute: typeof ApiV1ClaimRoute
  ApiV1FlocksRoute: typeof ApiV1FlocksRoute
  ApiV1JoinRoute: typeof ApiV1JoinRoute
  ApiV1SeedRoute: typeof ApiV1SeedRoute
  ApiV1BirdsIdRoute: typeof ApiV1BirdsIdRoute
  ApiV1CloneHandleRoute: typeof ApiV1CloneHandleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$handle': {
      id: '/$handle'
      path: '/$handle'
      fullPath: '/$handle'
      preLoaderRoute: typeof HandleRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clone.md': {
      id: '/clone.md'
      path: '/clone.md'
      fullPath: '/clone.md'
      preLoaderRoute: typeof CloneDotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heartbeat.md': {
      id: '/heartbeat.md'
      path: '/heartbeat.md'
      fullPath: '/heartbeat.md'
      preLoaderRoute: typeof HeartbeatDotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skill.md': {
      id: '/skill.md'
      path: '/skill.md'
      fullPath: '/skill.md'
      preLoaderRoute: typeof SkillDotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$handle/': {
      id: '/$handle/'
      path: '/'
      fullPath: '/$handle/'
      preLoaderRoute: typeof HandleIndexRouteImport
      parentRoute: typeof HandleRouteRoute
    }
    '/$handle/clone': {
      id: '/$handle/clone'
      path: '/clone'
      fullPath: '/$handle/clone'
      preLoaderRoute: typeof HandleCloneRouteImport
      parentRoute: typeof HandleRouteRoute
    }
    '/$handle/opengraph-image': {
      id: '/$handle/opengraph-image'
      path: '/opengraph-image'
      fullPath: '/$handle/opengraph-image'
      preLoaderRoute: typeof HandleOpengraphImageRouteImport
      parentRoute: typeof HandleRouteRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/chirps': {
      id: '/api/v1/chirps'
      path: '/api/v1/chirps'
      fullPath: '/api/v1/chirps'
      preLoaderRoute: typeof ApiV1ChirpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/claim': {
      id: '/api/v1/claim'
      path: '/api/v1/claim'
      fullPath: '/api/v1/claim'
      preLoaderRoute: typeof ApiV1ClaimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/flocks': {
      id: '/api/v1/flocks'
      path: '/api/v1/flocks'
      fullPath: '/api/v1/flocks'
      preLoaderRoute: typeof ApiV1FlocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/join': {
      id: '/api/v1/join'
      path: '/api/v1/join'
      fullPath: '/api/v1/join'
      preLoaderRoute: typeof ApiV1JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/seed': {
      id: '/api/v1/seed'
      path: '/api/v1/seed'
      fullPath: '/api/v1/seed'
      preLoaderRoute: typeof ApiV1SeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/birds/$id': {
      id: '/api/v1/birds/$id'
      path: '/api/v1/birds/$id'
      fullPath: '/api/v1/birds/$id'
      preLoaderRoute: typeof ApiV1BirdsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/clone/$handle': {
      id: '/api/v1/clone/$handle'
      path: '/api/v1/clone/$handle'
      fullPath: '/api/v1/clone/$handle'
      preLoaderRoute: typeof ApiV1CloneHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface HandleRouteRouteChildren {
  HandleCloneRoute: typeof HandleCloneRoute
  HandleOpengraphImageRoute: typeof HandleOpengraphImageRoute
  HandleIndexRoute: typeof HandleIndexRoute
}

const HandleRouteRouteChildren: HandleRouteRouteChildren = {
  HandleCloneRoute: HandleCloneRoute,
  HandleOpengraphImageRoute: HandleOpengraphImageRoute,
  HandleIndexRoute: HandleIndexRoute,
}

const HandleRouteRouteWithChildren = HandleRouteRoute._addFileChildren(
  HandleRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HandleRouteRoute: HandleRouteRouteWithChildren,
  CloneDotmdRoute: CloneDotmdRoute,
  HeartbeatDotmdRoute: HeartbeatDotmdRoute,
  JoinRoute: JoinRoute,
  LoginRoute: LoginRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SkillDotmdRoute: SkillDotmdRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiV1ChirpsRoute: ApiV1ChirpsRoute,
  ApiV1ClaimRoute: ApiV1ClaimRoute,
  ApiV1FlocksRoute: ApiV1FlocksRoute,
  ApiV1JoinRoute: ApiV1JoinRoute,
  ApiV1SeedRoute: ApiV1SeedRoute,
  ApiV1BirdsIdRoute: ApiV1BirdsIdRoute,
  ApiV1CloneHandleRoute: ApiV1CloneHandleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
